# Generated by Django 3.1.7 on 2021-03-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='question',
            new_name='all_text',
        ),
        migrations.RenameField(
            model_name='pinksetup',
            old_name='pinksetup_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pinksetup',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='pinksetup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pinksetup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
