# Generated by Django 3.1.7 on 2021-03-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0002_auto_20210318_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
