# Generated by Django 3.1.7 on 2021-03-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0003_delete_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('all_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinksetup.pinksetup')),
            ],
        ),
    ]
