# Generated by Django 3.1.7 on 2021-03-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0004_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='favorite_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='all_text',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='votes',
            new_name='vote',
        ),
    ]
