# Generated by Django 3.1.7 on 2021-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0005_auto_20210324_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorites',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
