# Generated by Django 3.1.7 on 2021-03-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0006_auto_20210324_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
    ]
