# Generated by Django 3.1.7 on 2021-03-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0008_auto_20210324_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
