# Generated by Django 3.1.7 on 2021-03-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0009_auto_20210324_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='vote',
        ),
    ]
