# Generated by Django 3.1.7 on 2021-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0011_remove_pinksetup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinksetup',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
