# Generated by Django 3.1.7 on 2021-03-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0012_pinksetup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinksetup',
            name='name',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
