# Generated by Django 3.1.7 on 2021-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinksetup', '0014_auto_20210325_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
